### ISSUE TITLE
我下载了,放到了手机根目录auto.js文件夹里面,启动Ant_Forest_Launcher报错

### ISSUE THREAD

**Issue by hywdyy** [SuperMonster003/Ant_Forest#12]
报错原因  10:22:33.285/E:TypeError: Cannot find functionwaitFor in object
function(mode){...}(<main>#5) at scriptt(<main>:5)

**Comment by SuperMonster003** [comment]
请提供Auto.js的版本

**Comment by hywdyy** [comment]
Version 3.0.0 bata3  
手机是魅族pro5

**Comment by SuperMonster003** [comment]
版本太老旧了 请按README.md的说明使用提供的版本

**Comment by hywdyy** [comment]
好 我试试
