### ISSUE TITLE
支付宝更新至 10.1.62 无法返回的问题

### ISSUE THREAD

**Issue by ljx0623** [SuperMonster003/Ant_Forest#13]
Auto.js版本：4.1.0 Alpha5
手机：小米5
系统版本：MIUI 10.2稳定版

现象：
支付宝更新至10.1.62后运行脚本，
1、获取好友能量或帮收能量后，无法返回至排行榜，若返回排行榜超时前手动返回，可以继续运行；
2、运行至排行榜底部，无法返回蚂蚁森林主页，若手动返回，则可以成功弹出统计信息

解决方法：
把第370行、第1221行、第1406行的
`clickObject(kw_back_btn) || keycode(4)`
修改为
`keycode(4) || clickObject(kw_back_btn)`
问题解决

结论：
`let kw_back_btn = id("com.alipay.mobile.nebula:id/h5_tv_nav_back")`
这个语句可能获取失败，建议获取之后判断一下再执行
`clickObject(kw_back_btn)`
或者直接执行
`keycode(4)`

最后祝楼主五一快乐，好人一生平安！~

**Comment by SuperMonster003** [comment]
感谢反馈 今晚之前会尝试适配支付宝62版本 请关注更新
:smile:

**Comment by SuperMonster003** [comment]
已于 `v1.6.1` - `2019/05/01` 尝试修复此问题
