### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by Cheney93** [SuperMonster003/Ant_Forest#2]
00:26:59.217/E: Error: Module "/storage/emulated/0/脚本/Ant_Forest_Project/Modules/__dialogs__pro_v6.js" not found. (file:///android_asset/modules/jvm-npm.js#93)
Error: Module "/storage/emulated/0/脚本/Ant_Forest_Project/Modules/__dialogs__pro_v6.js" not found.
    at Require (file:///android_asset/modules/jvm-npm.js:93:0)
    at /storage/emulated/0/脚本/Ant_Forest_Project/Tools/!Ant_Forest_Settings.js:5:0

**Comment by SuperMonster003** [comment]
模块已上传
