### ISSUE TITLE
Github_Material 里面内容太多，clone 周期长

### ISSUE THREAD

**Issue by tanxiaoluo** [SuperMonster003/Ant_Forest#5]
Github_Material 里面东西略多，clone 比较费时间

看了一下，主要是 auto.js 的几个 apk 包比较大，建议替换成 auto.js 项目 release 包下载的地址

原因有两个：
1. 从官方源下载，可信度高
2. 降低大家同步本仓库时间

**Comment by SuperMonster003** [comment]
感谢提出意见
官方GitHub已很久不提供新版本APK下载包了
我下午看看有没有更合适的方式

**Comment by SuperMonster003** [comment]
已于 `v1.5.7` - `2019/04/17` 缩减仓库体积

**Comment by SuperMonster003** [comment]
> 
> 
> Github_Material 里面东西略多，clone 比较费时间
> 
> 看了一下，主要是 auto.js 的几个 apk 包比较大，建议替换成 auto.js 项目 release 包下载的地址
> 
> 原因有两个：
> 
>     1. 从官方源下载，可信度高
> 
>     2. 降低大家同步本仓库时间

虽然问题已经关闭好久了 但我刚刚一直折腾到Git命令半夜12点半 终于成功真正缩减仓库体积了
😅
