### ISSUE TITLE
小米9，无法自动解锁

### ISSUE THREAD

**Issue by lwh201314** [SuperMonster003/Ant_Forest#6]
亮屏后要先上滑才能输入密码
![Screenshot_2019-04-18-07-48-34-568_org autojs autojspro](https://user-images.githubusercontent.com/33437578/56327912-1cb05500-61af-11e9-8c69-22f09f7fa971.png)

**Comment by SuperMonster003** [comment]
脚本是最新版本吗

**Comment by lwh201314** [comment]
![Screenshot_2019-04-18-08-11-14-860_org autojs autojspro](https://user-images.githubusercontent.com/33437578/56328448-9cd7ba00-61b1-11e9-8707-e93581582f88.png)
最新的看它上划了好几次才进入输密码界面，然后就灭屏了

**Comment by SuperMonster003** [comment]
上滑好几次是因为脚本再用时间增量方式自动尝试可用的滑动时间 成功之后会自动记录最佳的时间数据到存储中 下次就不会重新尝试而是直接使用这个数据值滑屏了
解锁方式的问题我先考虑一下 稍后回复

**Comment by SuperMonster003** [comment]
最新版的 `Tools` 文件夹里有一个 `Inspect_Lock_Screen_Layout.js`
这个锁屏布局采集工具
可以尝试把锁屏信息发送给我

**Comment by lwh201314** [comment]
[!Debug_Info.zip](https://github.com/SuperMonster003/Ant_Forest/files/3092804/Debug_Info.zip)
好像没有采集到锁屏布局

**Comment by SuperMonster003** [comment]
zip包太小了 而且打不开
文件夹里有几个文件
应该有3个截图文件和一个txt文件

**Comment by lwh201314** [comment]
[!Debug_Info.zip](https://github.com/SuperMonster003/Ant_Forest/files/3092836/Debug_Info.zip)

**Comment by SuperMonster003** [comment]
看到了里面的内容
滑动屏幕之后是指纹解锁
可以通过某种操作更换解锁方式吗
比如点击一下指纹图标就出现密码解锁了之类的
脚本只支持密码解锁/PIN解锁/图案解锁

**Comment by lwh201314** [comment]
![Screenshot_2019-04-18-13-27-40-964_lockscreen](https://user-images.githubusercontent.com/33437578/56338720-cb6b8a00-61dd-11e9-8a4a-e5c6ff9f23b3.png)
滑动后是这个界面

**Comment by SuperMonster003** [comment]
好的
麻烦把46行sleep(800)改成sleep(3000)试一下
可能是滑动后间隔太短 导致解锁页面控件没有抓取全
现在的滑动页面只抓取到了指纹控件

**Comment by lwh201314** [comment]
[!Debug_Info.zip](https://github.com/SuperMonster003/Ant_Forest/files/3092934/Debug_Info.zip)
![Screenshot_2019-04-18-13-50-37-176_org autojs autojspro](https://user-images.githubusercontent.com/33437578/56339494-1d61df00-61e1-11e9-843c-19cb91d956fa.png)
一样诶

**Comment by SuperMonster003** [comment]
好的 我下午回去帮你适配一下

**Comment by SuperMonster003** [comment]
已于 `v1.5.10` - `2019/04/18` 增加适配此机型自动解锁方案

**Comment by lwh201314** [comment]
用了最新脚本，自动上滑了几十次也没有到输密码解锁界面，手动上滑到解锁界面不会自动输密码

**Comment by SuperMonster003** [comment]
有日志报错吗
如果是前几次滑动的时候手动辅助一下
后面能自动输密码吗

**Comment by lwh201314** [comment]
![Screenshot_2019-04-18-19-43-49-168_org autojs autojspro](https://user-images.githubusercontent.com/33437578/56358817-641bfd00-6212-11e9-9c6b-63d3db055ad2.png)
这次自动上滑成功了，就是不会输密码

**Comment by SuperMonster003** [comment]
好 今晚尝试修复

**Comment by SuperMonster003** [comment]
`286行`
```
let click_keypad = num => click(keypads[num || 11].x, keypads[num || 11].y);
```
改为
```
let click_keypad = num => {
click(keypads[num || 11].x, keypads[num || 11].y);
log(keypads[num || 11].x, keypads[num || 11].y);
}
```
开启指针位置选项  
在开发者选项里面打开或者在auto.js软件悬浮窗里也可打开  

测试脚本  
看日志有没有显示出6个坐标点  
再通过指针位置看屏幕有没有点击的迹象

**Comment by lwh201314** [comment]
指针位置显示在输密码的界面还在上滑解锁，没有在点击输密码

**Comment by SuperMonster003** [comment]
> 
> 
> 指针位置显示在输密码的界面还在上滑解锁，没有在点击输密码


[MODULE_UNLOCK.zip](https://github.com/SuperMonster003/Ant_Forest/files/3096709/MODULE_UNLOCK.zip)
试试这个

**Comment by lwh201314** [comment]
这下会自动输密码了，但是不会自动上滑

**Comment by SuperMonster003** [comment]
好 周一晚前会发布试修版本

**Comment by SuperMonster003** [comment]
已于 `v1.5.14` - `2019/04/22` 尝试修复此问题

**Comment by lwh201314** [comment]
解决了，用最新的脚本可以了，感谢
