### ISSUE TITLE
怀疑 作者代码留了后门？

### ISSUE THREAD

**Issue by Ezoio** [SuperMonster003/Ant_Forest#7]
为何我发现我支付宝添加一个好友 ，名为 “心上秋”  ，正在review 作者脚本代码，，，只是猜测 不敢定论啊

**Comment by SuperMonster003** [comment]
哈哈 没关系的
代码就在那里 大家可以随便排查
若任何人发现任何恶意代码或者所谓的后门
我立即当众道歉并永远关停此项目
