### ISSUE TITLE
有没有办法获取 好友是否使用了能量保护罩 ？

### ISSUE THREAD

**Issue by koftt** [SuperMonster003/Ant_Forest#9]
想要获取好友是否使用能量保护罩，  用了就不收   始终不知怎么得知好友是否获取好友保护罩 感觉那个绿色的圈圈都没有组件的 不知怎么获取 关键代码在哪？。。。

**Comment by SuperMonster003** [comment]
此项目对于能量保护罩检测是基于区域颜色检测为主以及好友动态列表为辅的方式确定是否使用能量罩的  
一般第一部区域颜色判断就可以确定是否使用能量罩  
即便偶尔出错 (到目前还为发现) 动态列表里的信息也会确保不会出现误判的情况  
至于关键代码 可以阅读 `Ant_Forest.js` 中 `blacklistCheckThread()` 的相关代码
